export const portfolio = {
  name: "Rolando Remolacio",
  firstName: "Rolando",
  lastName: "Remolacio",
  suffix: "Jr.",
  role: "Full Stack Developer",
  location: "San Pedro, Laguna, Philippines",
  experience: "3+ Years",
  established: "2023",
  availableFor: "Freelance",
  version: "2.0.0",
  lastUpdated: "August 23, 2026",
  coordinates: {
    latitude: "14.3595°",
    longitude: "121.0473° E",
  },
  cvPath: "/assets/cv/rolando-remolacio-cv.pdf",
  connectLabel: "Let's Connect",
  navigation: ["Home", "About", "Experience", "Projects", "Skills", "Blog", "Contact"],
  socials: {
    github: "https://github.com/paynuj1099",
    linkedin: "https://www.linkedin.com/in/rolando-remolacio/",
    email: "rolandojrremolacio@gmail.com",
    phone: "+639666681237",
  },
  hero: {
    eyebrow: "Hello, I'm",
    description: [
      "I transform ideas into elegant, efficient code.",
      "Building modern web applications that solve real-world problems.",
    ],
    primaryCta: { label: "View My Work", href: "#projects" },
    secondaryCta: { label: "Download CV" },
    socialsLabel: "Find Me On",
    scrollLabel: "Scroll Down",
  },
  about: {
    kicker: "02. / About",
    heading: {
      line1: "I Design, Code,",
      line2: "And Solve Problems",
      line3Prefix: "With",
      highlight1: "Clean",
      line3Suffix: "And",
      highlight2: "Efficient",
      line4Suffix: "Solutions.",
    },
    detailsHeading: "More Than Just Code",
    paragraphs: [
      "As a Full Stack Developer with 3+ years of experience, I build robust, scalable applications using .NET, C#, React, and TypeScript. My experience spans both frontend and backend development.",
      "I enjoy turning complex business requirements into intuitive, maintainable products through continuous learning, careful attention to detail, and clean engineering practices.",
    ],
    facts: {
      role: { label: "Role", value: "Full Stack\nDeveloper" },
      location: { label: "Location", value: "Philippines" },
      experience: { label: "Experience", value: "3+ Years" },
    },
    technologies: [
      { name: ".NET", logo: "/assets/technologies/dotnet.svg" },
      { name: "React", logo: "/assets/technologies/react.svg" },
      { name: "C#", logo: "/assets/technologies/csharp.svg" },
      { name: "Azure", logo: "/assets/technologies/azure.svg" },
      { name: "Next.js", logo: "/assets/technologies/nextjs.svg" },
      { name: "TypeScript", logo: "/assets/technologies/typescript.svg" },
      { name: "Node.js", logo: "/assets/technologies/nodejs.svg" },
      { name: "SQL", logo: "/assets/technologies/sql-server.svg" },
      { name: "MongoDB", logo: "/assets/technologies/mongodb.svg" },
      { name: "Docker", logo: "/assets/technologies/docker.svg" },
      { name: "Git", logo: "/assets/technologies/git.svg" },
      { name: "REST APIs", logo: "/assets/technologies/rest-api.svg" },
    ],
    profileImage: "/assets/about/profile.png",
    profileImageVersion: "2026-08-24-0241",
    profileFrameImage: "/assets/about/frame.png",
    signatureImage: "/assets/about/signature.png",
    signatureImageVersion: "2026-08-24-0302",
  },
  education: {
    degree: "BS in Computer Engineering",
    school: "Cavite State University - Carmona",
    graduated: "2023",
    description: "Built a strong foundation in programming, database management, and software development.",
  },
  certifications: [
    {
      type: "Microsoft Certificate of Achievement",
      title: "Developing ASP.NET MVC Web Applications",
      issuer: "MISNet Education Inc.",
      detail: "Makati City",
      date: "August 19–23, 2024",
      image: "/assets/certifications/microsoft_mvc_training_certificate.png",
    },
    {
      type: "Certificate of Completion",
      title: "Online Placement Test in English",
      issuer: "Berlitz",
      detail: "Level 8 / CEFR Level B2.1",
      date: "",
      image: "/assets/certifications/berlitz-online-placement-test-english-certificate.png",
    },
  ],
  experiences: [
    {
      role: "Full Stack Developer",
      company: "Practice AI",
      arrangement: "Remote",
      period: "December 2025 – June 2026",
      description: "Developed SaaS features for legal technology using .NET, Blazor, Microsoft Azure, and Azure OpenAI, including document processing, litigation support, payment integration, microservices, automated testing, and CI/CD.",
    },
    {
      role: "Programmer | Analyst II",
      company: "Vertere Global Solutions, Inc.",
      arrangement: "Hybrid",
      period: "April 2025 – December 2025",
      description: "Developed data-intensive enterprise applications for Toyota Motor Philippines using React, .NET, and SQL Server, including legacy modernization, sales forecasting, reporting, database optimization, and SSIS workflows.",
    },
    {
      role: "Full Stack Developer",
      company: "ROHM Electronics Philippines, Inc.",
      arrangement: "On-site",
      period: "May 2023 – April 2025",
      description: "Built internal web and Windows applications that digitized manufacturing workflows, automated data collection, and provided production dashboards using .NET, C#, VB.NET, JavaScript, Node.js, and SQL Server.",
    },
  ],
  projectsArchiveUrl: "https://www.rolandoremolacio.com/#projects",
  featuredProjects: [
    {
      number: "01",
      title: "Verde by Renzo",
      category: "Full Stack",
      description: "Premium e-commerce platform for a golf/lifestyle brand with storefront, admin dashboard, product and order management, and payments integration.",
      image: "/assets/projects/verde-by-renzo.png",
      imageAlt: "Dark premium golf e-commerce storefront for Verde by Renzo",
      technologies: ["Next.js", "TypeScript", "Firebase", "Tailwind CSS", "PayMongo"],
      liveUrl: "https://verde-by-renzo.vercel.app/",
      githubUrl: "https://github.com/paynuj1099/verde-by-renzo",
    },
    {
      number: "02",
      title: "Practice AI",
      category: "SaaS",
      description: "AI-powered legal SaaS that helps users analyze documents, generate summaries, and automate case insights.",
      image: "/assets/projects/practice-ai.png",
      imageAlt: "Dark Practice AI legal document analysis dashboard",
      technologies: [".NET", "Azure", "MongoDB", "Docker", "Azure OpenAI"],
      liveUrl: "#contact",
    },
    {
      number: "03",
      title: "JobTrackr",
      category: "Mobile App",
      description: "Job application tracker built with React Native and Expo to track, organize, and manage job applications.",
      image: "/assets/projects/jobtrackr.png",
      imageAlt: "Angled smartphone displaying the JobTrackr application dashboard",
      technologies: ["React Native", "Expo", "TypeScript"],
      liveUrl: "#contact",
    },
  ],
  projects: [
    {
      name: "Verde by Renzo",
      category: "Full Stack Web",
      description: "Premium golf e-commerce platform with authentication, Firestore product data, PayMongo payments, order tracking, customer accounts, and an administration dashboard.",
      technologies: ["Next.js", "React", "TypeScript", "Firebase", "PayMongo"],
      liveUrl: "https://verde-by-renzo.vercel.app/",
      codeUrl: "https://github.com/paynuj1099/verde-by-renzo",
    },
    {
      name: "Website Auditor Tool",
      category: "Full Stack Web",
      description: "Website auditing and SEO analysis tool with structured insights, scoring, analytics, and actionable recommendations.",
      technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Recharts"],
      liveUrl: "https://seoauditor-nu.vercel.app/",
    },
    {
      name: "Product Landing Page",
      category: "Frontend Web",
      description: "Interactive product showcase combining responsive layouts with real-time browser-based 3D presentation.",
      technologies: ["React", "TypeScript", "Three.js", "Vite"],
      liveUrl: "https://productlandingpage-ten.vercel.app/",
      codeUrl: "https://github.com/paynuj1099/React3DThreeJS",
    },
    {
      name: "Assisteon Staffing",
      category: "Frontend Web",
      description: "Professional staffing platform with lead-generation features and a custom internal analytics dashboard.",
      technologies: [".NET Core", "C#", "JavaScript", "Razor Pages"],
      liveUrl: "https://assisteonstaffing.com/",
    },
    {
      name: "Modern Portfolio Website",
      category: "Full Stack Web",
      description: "Motion-focused developer portfolio with responsive layouts, dark mode, animated interfaces, and interactive project presentation.",
      technologies: ["React", "TypeScript", "Tailwind CSS", "GSAP"],
      liveUrl: "https://modern-portfolio-vert-pi.vercel.app/",
      codeUrl: "https://github.com/paynuj1099/modern-portfolio",
    },
    {
      name: "Data Mapping Automation",
      category: "Full Stack Windows",
      description: "Internal desktop application that automates data mapping, transformation, validation, and SQL Server workflows.",
      technologies: [".NET Windows Forms", "C#", "Microsoft SQL Server"],
    },
  ],
  skills: {
    backend: [".NET / .NET Core", "C#", "VB.Net", "Node.js", "PHP", "REST APIs"],
    frontend: ["JavaScript", "TypeScript", "React", "Next.js", "Blazor", "Tailwind CSS"],
    databases: ["Microsoft SQL Server", "MySQL", "MongoDB", "Database Design"],
    devops: ["Azure DevOps", "CI/CD", "Jira"],
    architecture: ["MVC", "Microservices", "API Design", "System Design", "Prompt Engineering"],
    tools: ["Claude AI", "GitHub Copilot", "Azure OpenAI", "Git", "GitHub", "Azure Repos"],
  },
  blogPosts: [
    { title: "Clean Code Principles: Writing Code That Developers Can Read", date: "March 5, 2026" },
    { title: "Web Performance Optimization: Making Your Site Lightning Fast", date: "February 10, 2026" },
    { title: "Building Production-Ready REST APIs: A Comprehensive Guide", date: "January 15, 2026" },
  ],
  contact: {
    heading: "Let's Build Something Amazing Together",
    description: "I'm always interested in new opportunities and exciting projects. Whether you have a project in mind or simply want to connect, I'd love to hear from you.",
  },
} as const;
